### ISSUE TITLE
Installing Lpy on Windows

### ISSUE THREAD

**Issue by RomainBarillot** [openalea/lpy#17]
Hi,
I am trying to install Lpy on a Windows 10 machine from Conda.

I have installed Conda but I can't install Lpy
The command `conda create -n lpy openalea.lpy openalea.plantgl 'boost =1.66.0' -c openalea` raises the following error:
```
Solving environment: failed
PackagesNotFoundError: The following packages are not available from current channels:
  - openalea.lpy
  - openalea.plantgl
```

**Comment by RomainBarillot** [comment]
As seen with @christian34, the windows installer is no longer available on the openalea.plantgl channel.
As a temporary solution, I have download plangtl from the label\unstable channel.

**Comment by pradal** [comment]
I will open an other issue for the IPython shell: #18
