### ISSUE TITLE
Get attributes back when launching lpy by batch processing

### ISSUE THREAD

**Issue by SimonRouet** [openalea/lpy#19]
Hello,

I am using a Lsystem and I would like to do a sensitivity analysis.
I wrote a python script to execute the lpy file and I want to get some attributes of the Lsystem back (for instance a dictionnary).
Presently, I use MyLsystem.derive() to execute the .lpy file but no access to attributes is possible. It seems close the Lsystem.
Is there an other method than .derive() to use ?

Kind regards,
Simon

**Comment by fredboudon** [comment]
Once the model has run, you can access the global variable of the model as a standard attribute of the lsystem:
For instance, if you have a global variable in your lsystem
nbleaf = 0
You can do
lsystem.derive()
nbleaf = lsystem.nbleaf
You can also access to all element of the simulation with 
lsystem.execContext().globals() and lsystem.execContext().locals()
