### ISSUE TITLE
lpy launcher activate apparently hard coded 'openalea'  conda environment

### ISSUE THREAD

**Issue by christian34** [openalea/lpy#20]
@fredboudon 
After installing lpy in conda environment named my_env, runing : 
activate my_env
lpy

launch 'call activate openalea'

...which is a bit weird I suppose

**Comment by fredboudon** [comment]
This is only true for code in training sessions. This was to allow students to just double click on the lpy.bat file and have lpy running. The same file can be copied and edit for your environment.

**Comment by christian34** [comment]
Oups sorry ! I didn't realise a lpy batch was there....
