### ISSUE TITLE
Can't install on Ubuntu 20.04 - UnsatisfiableError

### ISSUE THREAD

**Issue by ArnaudBvr** [openalea/lpy#24]
Hello,
Using the command from the documentation `conda create -n lpy openalea.lpy -c openalea` throws an error on Ubuntu 20.04. 

The error : 
```
UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

After some snooping around, it seems the error is not directly related to CUDA driver but rather to other unsatisfied dependecies. I tried some of the workarounds proposed in issue #12 , but to no avail.

Any advice on how to install on a recent Ubuntu install ?

Regards, 
Arnaud Bouvry
Liège University

**Comment by ArnaudBvr** [comment]
Update : hoping for a miracle, I tried `conda create -n lpy -c openalea -c conda-forge openalea.lpy boost=1.66.0 nose` from Issue #23 (1st post in that thread), which allowed me to install LPy for the first time. Yay, success ! 

However, I now get a different error when trying to run LPy.

```
$ lpy
Traceback (most recent call last):
  File "/home/gxbouvry/anaconda3/envs/lpy/bin/lpy", line 11, in <module>
    load_entry_point('OpenAlea.Lpy==2.7.1', 'gui_scripts', 'lpy')()
  File "/home/gxbouvry/anaconda3/envs/lpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/gxbouvry/anaconda3/envs/lpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/gxbouvry/anaconda3/envs/lpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/gxbouvry/anaconda3/envs/lpy/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/gxbouvry/anaconda3/envs/lpy/lib/python2.7/site-packages/OpenAlea.Lpy-2.7.1-py2.7-linux-x86_64.egg/openalea/lpy/__init__.py", line 2, in <module>
    from __lpy_kernel__ import *
ImportError: libmpfr.so.4: cannot open shared object file: No such file or directory

```

Any help would be much appreciated !
Arnaud B.

**Comment by jvail** [comment]
Not sure if you are bound to a particular version but you could try this version.  Does works for me with debian 10.

`conda create -y -n lpy -c fredboudon openalea.lpy`

**Comment by ArnaudBvr** [comment]
Thanks a lot for the reactivity !
Unfortunately, this throws the same error as in my original post, and when trying to apply the same workaround as in my 2nd post it failed. Not much luck yet, unfortunately !

**Comment by jvail** [comment]
The same error? Should at least be slightly different since it is py 3. Did you try to install libmpfr on ubuntu?

**Comment by ArnaudBvr** [comment]
So the `-c fredboudon` changes the conda channel and gives access to a python3 implementation of openalea, if I understand correctly ?

Here is the command (so you can check that I used it correctly) and the subsequent error. 

```
$ conda create -n lpy -c fredboudon openalea.lpy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

**Comment by jvail** [comment]
> So the `-c fredboudon` changes the conda channel and gives access to a python3 implementation of openalea, if I understand correctly ?

Yes

> Here is the command (so you can check that I used it correctly) and the subsequent error.
> UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver:
> 
>   - feature:/linux-64::__cuda==10.2=0
> 
> Your installed CUDA driver is: 10.2
> ```

Ok, sorry. Thought you were stuck at step two. 

> After some snooping around, it seems the error is not directly related to CUDA driver but rather to other unsatisfied dependecies`

So it is not a driver issue? What was the missing dependency here?

**Comment by ArnaudBvr** [comment]
To address the last point : I do not remember the specifics, but I read somewhere on stackoverflow that the CUDA driver is not particularly to blame. For example, the events from my 1st and 2nd post lead me to believe that the problem lied with the boost dependency, since adding `-c conda-forge [...] boost=1.66.0` partially resolved the issue.

Also : 

> Did you try to install libmpfr on ubuntu?

Yes I did  try and it did not help.

**Comment by jvail** [comment]
Ok. I gave it a try myself (also with ubuntu) but it seems something is currently broken with the linux files in the @fredboudon conda channel  (guess I previously had a locally cached version in conda so it seemed to work - sorry).

```
conda create -v -y -n lpy -c fredboudon openalea.lpy
Collecting package metadata (current_repodata.json): ...working... Unable to retrieve repodata (response: 404)
for https://conda.anaconda.org/fredboudon/linux-64/current_repodata.json
```

I opened an issue there https://github.com/fredboudon/lpy/issues/13#issue-679144882

**Comment by ArnaudBvr** [comment]
Okay, thanks a lot for taking the time to try and help me ! Frustrations indeed.

**Comment by jvail** [comment]
Wait! Mysteriously this (with version no) seems to work (at least it fetches the packages): conda create -y -n lpy -c fredboudon -c conda-forge 'openalea.lpy>=3.4.0'

**Comment by jvail** [comment]
I only tried in an ubuntu docker and it looks good. At least no UnsatisfiableError. I still get an error but that is expected since there are no graphics driver:

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::pyopengl-3.1.5-py_0'. 
```

**Comment by ArnaudBvr** [comment]
> Wait! Mysteriously this (with version no) seems to work (at least it fetches the packages): conda create -y -n lpy -c fredboudon -c conda-forge 'openalea.lpy>=3.4.0'

This worked ! I did'nt run any script or example yet but the env build worked and I can open the GUI. Solved !
I could not have found this by myself so thank you very much for your valuable insight !

Regards, 
Arnaud B.

**Comment by ArnaudBvr** [comment]
I can now confirm that it (mostly) works. There are some compatibility issues with the scripts from the initial paper, but I believe it is difficult to modify for transparency reasons. 
Thanks again @jvail !

**Comment by jvail** [comment]
@ArnaudBvr great, you're welcome

**Comment by jvail** [comment]
Finally ... I actually forgot including `-c conda-forge` in my first suggestion. Then it does work as well w/o a version:

`conda create -v -y -n lpy -c fredboudon -c conda-forge openalea.lpy`
