### ISSUE TITLE
[bug] indentation error on comments

### ISSUE THREAD

**Issue by jannessm** [openalea/lpy#26]
The .lpy interpreter says that in the following example is an indentation error, caused by the comments. I would expect that the interpreter ignores them.

### test.lpy
```
Axiom: F
decomposition: # beginning of decomposition rules.
               # These rules are applied recursively after each production step
               # usefull to decompose a module into a structure
F --> F
```

### script.py
```python
l = Lsystem("test.lpy")
```

**Comment by fredboudon** [comment]
Comment should start at the beginning of the line in the rule section. decomposition (or production) is not supposed to be a traditional code block.
