### ISSUE TITLE
input() not working

### ISSUE THREAD

**Issue by syralie** [openalea/lpy#32]
Hi, I am trying to use input() in our code in the L-Py GUI. However when I click run, it lags and endlessly tries to load. Eventually I just press ^C in the terminal to interrupt it. I am on macOS Monterey with L-Py on python 3.9. On another laptop (Windows) with a python 3.8 version of L-Py, it gives an error message about sys.stdin (might be another name, can't quite remember but can confirm it was "sys").

Is this normal? I had thought pure python code should work. Is there any alternative method?

**Comment by fredboudon** [comment]
In the gui, the input command is not usable. Sorry for that.
Even in the shell use of lpy it is not recommended to use such blocking function.
